name: Create SBOM 1 2
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cve_scan:
    name: Generate SBOM
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
     
#       - name: Get date
#         id: get-date
#         run: |
#           echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
#       -  name: Get cached database
#          uses: actions/cache@v2
#          with:
#           path: ~/.cache/cve-bin-tool
#           key: ${{ runner.os }}-cve-bin-tool-${{ steps.get-date.outputs.date }}
#       - name: Install dependencies and cve-bin-tool
#         run: |
#           python -m pip install --upgrade pip
#           pip install cve-bin-tool
#           python -m pip install --upgrade setuptools
#           python -m pip install --upgrade wheel
      - name: Install Cyclone DX
        run : |
          pip install cyclonedx-bom

        
      - name: Generate requirements
        run: |
          pip freeze > requirements.txt
          dir
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads    
      - name: Generate SBOM
        run: |
          cd downloads
          cyclonedx-bom -r
          cd ..
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads   

#          dir
#       - name: Generate Report
#         uses: actions/upload-artifact@v2
#         with:
#           name: XML_Report
#           path: cyclonedx.xml
#       - name: Scan SBOM
#         run: |
#            cve-bin-tool --sbom cyclonedx --sbom-file cyclonedx.xml
     
 
          
      
